In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./images/3_cars.jpg')

In [3]:
cv2.imshow('Original_image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img.shape

(795, 1200, 3)

In [5]:
b,g,r = cv2.split(img)

In [6]:
print(b)

[[43 33 36 ... 19 27 39]
 [28 12 11 ...  2  7 20]
 [28 15 16 ...  3 12 25]
 ...
 [60 49 48 ... 27 33 43]
 [58 48 47 ... 27 33 43]
 [75 64 63 ... 44 50 60]]


In [7]:
b.shape

(795, 1200)

In [15]:
cv2.imshow('Blue Image',b)
cv2.imshow('Green Image',g)
cv2.imshow('Red Image',r)
cv2.imshow('Original Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Convert_Color

In [16]:
img1 = cv2.imread('./images/beach.jpg')

In [17]:
cv2.imshow('Original BGR',img1)
cv2.waitKey(0)
cv2.destoryAllWindows()

AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

In [22]:
# BGR to Gray
gray = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

# BGR to RGB
img_rgb = cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)

# BGR to HSV
img_hsv = cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)

# BGR to LAB
img_lab = cv2.cvtColor(img1,cv2.COLOR_BGR2LAB)

cv2.imshow('Original- bgr',img1)
cv2.imshow('Greyscale',gray)
cv2.imshow('RGB IMAGE',img_rgb)
cv2.imshow('HSV IMAGE',img_hsv)
cv2.imshow('LAB IMAGE',img_lab)
cv2.waitKey(0)
cv2.destroyAllWindows()